import john from '../assets/girl-doc.jpg'; // Replace this with actual image imports

const doctorData = [
  {
    id: "1",
    name: "Dr. John Doe",
    specialty: "Cardiology",
    location: "New York",
    image: john,
  },
  {
    id: "2",
    name: "Dr. Jane Smith",
    specialty: "Neurology",
    location: "Los Angeles",
    image: john,
  },
  {
    id: "3",
    name: "Dr. Richard Roe",
    specialty: "Orthopedics",
    location: "Chicago",
    image: john,
  },
  {
    id: "4",
    name: "Dr. Emily Clark",
    specialty: "Pediatrics",
    location: "Houston",
    image: john,
  },
  {
    id: "1",
    name: "Dr. John Doe",
    specialty: "Cardiology",
    location: "New York",
    image: john,
  },
  {
    id: "2",
    name: "Dr. Jane Smith",
    specialty: "Neurology",
    location: "Los Angeles",
    image: john,
  },
  {
    id: "3",
    name: "Dr. Richard Roe",
    specialty: "Orthopedics",
    location: "Chicago",
    image: john,
  },
  {
    id: "4",
    name: "Dr. Emily Clark",
    specialty: "Pediatrics",
    location: "Houston",
    image: john,
  },
  {
    id: "1",
    name: "Dr. John Doe",
    specialty: "Cardiology",
    location: "New York",
    image: john,
  },
  {
    id: "2",
    name: "Dr. Jane Smith",
    specialty: "Neurology",
    location: "Los Angeles",
    image: john,
  },
  {
    id: "3",
    name: "Dr. Richard Roe",
    specialty: "Orthopedics",
    location: "Chicago",
    image: john,
  },
  {
    id: "4",
    name: "Dr. Emily Clark",
    specialty: "Pediatrics",
    location: "Houston",
    image: john,
  },
  {
    id: "1",
    name: "Dr. John Doe",
    specialty: "Cardiology",
    location: "New York",
    image: john,
  },
  {
    id: "2",
    name: "Dr. Jane Smith",
    specialty: "Neurology",
    location: "Los Angeles",
    image: john,
  },
  {
    id: "3",
    name: "Dr. Richard Roe",
    specialty: "Orthopedics",
    location: "Chicago",
    image: john,
  },
  {
    id: "4",
    name: "Dr. Emily Clark",
    specialty: "Pediatrics",
    location: "Houston",
    image: john,
  },
  {
    id: "1",
    name: "Dr. John Doe",
    specialty: "Cardiology",
    location: "New York",
    image: john,
  },
  {
    id: "2",
    name: "Dr. Jane Smith",
    specialty: "Neurology",
    location: "Los Angeles",
    image: john,
  },
  {
    id: "3",
    name: "Dr. Richard Roe",
    specialty: "Orthopedics",
    location: "Chicago",
    image: john,
  },
  {
    id: "4",
    name: "Dr. Emily Clark",
    specialty: "Pediatrics",
    location: "Houston",
    image: john,
  },
  {
    id: "1",
    name: "Dr. John Doe",
    specialty: "Cardiology",
    location: "New York",
    image: john,
  },
  {
    id: "2",
    name: "Dr. Jane Smith",
    specialty: "Neurology",
    location: "Los Angeles",
    image: john,
  },
  {
    id: "3",
    name: "Dr. Richard Roe",
    specialty: "Orthopedics",
    location: "Chicago",
    image: john,
  },
  {
    id: "4",
    name: "Dr. Emily Clark",
    specialty: "Pediatrics",
    location: "Houston",
    image: john,
  },
  // Add more doctors as needed
];

export default doctorData;
